services:
  - type: web
    name: yolo-video-app
    env: python
    plan: starter   # or higher if GPU needed
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
